### ISSUE TITLE
/home/*USER*/.dig/server_coin.json -  not found /.dig no files 

### ISSUE THREAD

**Issue by amnesia106** [DIG-Network/chia-dig-node#10]
```
[Error: EACCES: permission denied, open '/home/chia/.dig/server_coin.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/chia/.dig/server_coin.json'
}
```

```
chia@chiaDIG-VMware-Virtual-Platform:~/chia-dig-node$ 
cat /home/chia/.dig/server_coin.json
cat: /home/chia/.dig/server_coin.json: Datei oder Verzeichnis nicht gefunden
```

**Comment by johnathon-b** [comment]
What are the permissions on the files within the ~/.dig, or which ever path you're using.

```
ls -l /home/chia/.dig/server_coin.json
```

**Comment by amnesia106** [comment]
`chia@chiaDIG-VMware-Virtual-Platform:~/chia-dig-node$ ls -l /home/chia/.dig/server_coin.json
ls: Zugriff auf '/home/chia/.dig/server_coin.json' nicht möglich: Datei oder Verzeichnis nicht gefunden
`

but my dignode says.

` Sorted Public Listings by xchRewardPerEpoch: [
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    |   {
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    |     storeId: 'c7c0bc885b02531d42c72f11e90be6a22f76ac7d467acbfae76bc02d222>
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    |     xchRewardPerEpoch: 5
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    |   }
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    | ]
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    | Store Path: /.dig/stores/c7c0bc885b02531d42c72f11e90be6a22f76ac7d467acbfa>
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    | Store directory for c7c0bc885b02531d42c72f11e90be6a22f76ac7d467acbfae76bc>
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    | Subscription process completed.
Sep 29 09:57:37 chiaDIG-VMware-Virtual-Platform docker-compose[31964]: incentive-server-1    | Subscriber task completed.
`

**Comment by amnesia106** [comment]
my docker_config: 

```
cat docker-compose.yml
version: '3.8'

services:
  propagation-server:
    image: dignetwork/dig-propagation-server:latest-alpha
    ports:
      - "4159:4159"
    volumes:
      - /home/chia/.dig/remote:/.dig
    environment:
      - DIG_USERNAME=xxx
      - DIG_PASSWORD=xxx
      - DIG_FOLDER_PATH=/.dig
      - PORT=4159
      - REMOTE_NODE=1
      - TRUSTED_FULLNODE=not-provided
      - TRUSTED_FULLNODE_PORT=8444
    restart: always
    networks:
      - dig_network

  content-server:
    image: dignetwork/dig-content-server:latest-alpha
    ports:
      - "4161:4161"
    volumes:
      - /home/chia/.dig/remote:/.dig
    environment:
      - DIG_FOLDER_PATH=/.dig
      - PORT=4161
      - REMOTE_NODE=1
      - TRUSTED_FULLNODE=not-provided
      - TRUSTED_FULLNODE_PORT=8444
    restart: always
    networks:
      - dig_network

  incentive-server:
    image: dignetwork/dig-incentive-server:latest-alpha
    ports:
      - "4160:4160"
    volumes:
      - /home/chia/.dig/remote:/.dig
    environment:
      - DIG_USERNAME=xxx
      - DIG_PASSWORD=xxx
      - DIG_FOLDER_PATH=/.dig
      - PORT=4160
      - REMOTE_NODE=1
      - TRUSTED_FULLNODE=not-provided
      - TRUSTED_FULLNODE_PORT=8444
      - PUBLIC_IP=not-provided
      - DISK_SPACE_LIMIT_BYTES=1099511627776
      - MERCENARY_MODE=true
    restart: always
    networks:
      - dig_network

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/chia/.dig/remote/.nginx/conf.d:/etc/nginx/conf.d
      - /home/chia/.dig/remote/.nginx/certs:/etc/nginx/certs
    depends_on:
      - content-server
    networks:
      - dig_network
    restart: always

networks:
  dig_network:
    driver: bridge

```

i marked my dig username with xxx
